//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bootstrapASP
{
    using System;
    using System.Collections.Generic;
    
    public partial class alumnosF
    {
        public int id_alumno { get; set; }
        public string nombre { get; set; }
        public string apellidos { get; set; }
        public string f_nacimiento { get; set; }
    }
}
